[build]
builder = "NIXPACKS"

[deploy]
services = ["frontend", "backend"]

[[services]]
name = "frontend"
start_command = "npm install && npm run build && npm run preview"
path = "./apps/front"

[[services]]
name = "backend"
start_command = "npm install && npm run dev"
path = "./apps/back"